### ISSUE TITLE
Welcome text from Administration -> Settings -> Welcome text isn't converted

### ISSUE THREAD

**Issue by martinvonwittich** [Ecodev/redmine_convert_textile_to_markown#3]
As said in the subject, the Welcome text is not converted. Should be an easy fix :)

**Comment by PowerKiKi** [comment]
If you can find what to add in [that hash](https://github.com/Ecodev/redmine_convert_textile_to_markown/blob/master/convert_textile_to_markdown.rake#L2) and submit a PR, I'll merge it

**Comment by martinvonwittich** [comment]
Hmm, I have almost no Ruby experience. I have figured out that the welcome text is stored in the table `settings`:

```
redmine=# select id,name,updated_on,length(value) from settings where name = 'welcome_text';
 id |     name     |         updated_on         | length
----+--------------+----------------------------+--------
 13 | welcome_text | 2017-07-05 16:40:47.467379 |   1760
(1 Zeile)
```
But I don't know what I'd have to add to that hash to convert only the welcome_text. This would convert all settings, wouldn't it? I don't think that that would be a good idea.

```
Setting => [:value],
```

**Comment by PowerKiKi** [comment]
I'm not quite sure either... maybe doing that single value migration manually would be easier ?

**Comment by PowerKiKi** [comment]
Thanks !
